version: '3.8'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api-server
    tty: true
    ports:
      - 1323:1323
    env_file:
      - .env
    depends_on:
      - 'db'
    #command: ["/bin/sh", "-c","sh ./init/wait.sh"]
    command: ["./go-todo-api"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: todo-client
    tty: true
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: todo-db
    restart: unless-stopped
    volumes:
      - ./api/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 5432:5432
